name: Lint Commits

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml

