name: AWS EC2 Setup and Script Execution

on:
  push:
    branches:
      - main

jobs:
  create-run-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Specify your AWS region

      - name: Launch EC2 instance
        id: launch_ec2
        run: |
          USER_DATA=$(base64 -w 0 <<EOF
          #!/bin/bash
          sudo apt update
          curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh
          bash -E nodesource_setup.sh
          sudo npm install -g yarn
          npm create-strapi-app simple-strapi --quickstart
          cd simple-strapi
          yarn develop
          EOF
          )
          
          
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0e001c9271cf7f3b9 \
            --instance-type t2.medium \
            --key-name NV-PPK \
            --security-group-ids sg-02c9d7b34d30a2ac4 \
            --subnet-id subnet-03ead0e82bf80166e \
            --associate-public-ip-address \
            --user-data $USER_DATA \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV
          echo "Instance ID: $INSTANCE_ID"
          
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
          
